# Deployment — define cómo corren los pods del Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ops-dashboard
  labels:
    app: frontend
    project: ops-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ops-dashboard-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: API_URL
              value: "http://api:5000"  # Service name del backend
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10